const products = [
  {
    name: "Black Silk Evening Dress",
    description: "A floor-length gown cut from pure mulberry silk, with a bias drape that skims the body and a low cowl back. Made for black-tie rooms.",
    price: 24500,
    compareAtPrice: 28900,
    category: "Dresses",
    occasion: ["Formal Evening", "Party", "Date Night"],
    color: ["Black"],
    sizes: ["XS", "S", "M", "L"],
    material: "100% Mulberry Silk",
    images: ["https://images.unsplash.com/photo-1595777457583-95e059d581b8?w=800"],
    stock: 12,
    sku: "VLR-DR-001",
    tags: ["silk", "gown", "evening", "black tie", "elegant", "minimal"],
    featured: true,
    rating: 4.8,
    numReviews: 34,
  },
  {
    name: "Onyx Velvet Wrap Gown",
    description: "Deep-black stretch velvet wrap gown with a sculpted waist tie and dramatic trailing hem. Photographs beautifully under low light.",
    price: 27800,
    category: "Dresses",
    occasion: ["Formal Evening", "Wedding Guest"],
    color: ["Black"],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "Stretch Velvet",
    images: ["https://images.unsplash.com/photo-1566174053879-31528523f8ae?w=800"],
    stock: 8,
    sku: "VLR-DR-002",
    tags: ["velvet", "wrap", "evening", "black tie", "dramatic"],
    featured: true,
    rating: 4.7,
    numReviews: 21,
  },
  {
    name: "Ivory Satin Bridal Gown",
    description: "A structured satin bridal gown with a sweetheart neckline and cathedral train. Hand-finished French lace bodice.",
    price: 89000,
    category: "Dresses",
    occasion: ["Wedding"],
    color: ["Ivory", "White"],
    sizes: ["XS", "S", "M", "L"],
    material: "Duchess Satin, French Lace",
    images: ["https://images.unsplash.com/photo-1594552072238-b8a33785b261?w=800"],
    stock: 4,
    sku: "VLR-DR-003",
    tags: ["bridal", "wedding", "gown", "lace", "satin"],
    featured: false,
    rating: 4.9,
    numReviews: 12,
  },
  {
    name: "Emerald Green Cocktail Dress",
    description: "A knee-length cocktail dress in silk-blend crepe, with an asymmetric neckline and hidden side pockets.",
    price: 15800,
    category: "Dresses",
    occasion: ["Party", "Date Night", "Business"],
    color: ["Green", "Emerald"],
    sizes: ["XS", "S", "M", "L"],
    material: "Silk-blend Crepe",
    images: ["https://images.unsplash.com/photo-1539008835657-9e8e9680c956?w=800"],
    stock: 15,
    sku: "VLR-DR-004",
    tags: ["cocktail", "party", "crepe", "emerald"],
    featured: true,
    rating: 4.6,
    numReviews: 19,
  },
  {
    name: "Camel Wool Tailored Coat",
    description: "A single-breasted overcoat in Italian camel wool, cut with sharp shoulders and a knee-skimming hem.",
    price: 32500,
    category: "Outerwear",
    occasion: ["Business", "Casual"],
    color: ["Beige", "Tan"],
    sizes: ["S", "M", "L", "XL"],
    material: "Italian Wool",
    images: ["https://images.unsplash.com/photo-1544022613-e87ca75a784a?w=800"],
    stock: 10,
    sku: "VLR-OW-001",
    tags: ["coat", "wool", "tailored", "camel", "winter"],
    featured: false,
    rating: 4.7,
    numReviews: 27,
  },
  {
    name: "Black Tuxedo Blazer",
    description: "A satin-lapel tuxedo blazer in midnight black wool, tailored for a sharp, formal silhouette.",
    price: 28900,
    category: "Suits",
    occasion: ["Formal Evening", "Business"],
    color: ["Black"],
    sizes: ["S", "M", "L", "XL"],
    material: "Wool, Satin Lapel",
    images: ["https://images.unsplash.com/photo-1594938298603-c8148c4dae35?w=800"],
    stock: 9,
    sku: "VLR-SU-001",
    tags: ["tuxedo", "blazer", "formal", "black tie", "suit"],
    featured: true,
    rating: 4.8,
    numReviews: 16,
  },
  {
    name: "Navy Three-Piece Suit",
    description: "A modern-fit navy suit in Italian wool twill, with a matching waistcoat for formal or business occasions.",
    price: 34500,
    category: "Suits",
    occasion: ["Business", "Wedding"],
    color: ["Navy", "Blue"],
    sizes: ["S", "M", "L", "XL"],
    material: "Italian Wool Twill",
    images: ["https://images.unsplash.com/photo-1617137968427-85924c800a22?w=800"],
    stock: 11,
    sku: "VLR-SU-002",
    tags: ["suit", "navy", "business", "wedding", "three-piece"],
    featured: false,
    rating: 4.6,
    numReviews: 22,
  },
  {
    name: "Gold Strappy Heeled Sandals",
    description: "Metallic gold leather sandals with a slender 90mm heel and delicate ankle strap. Made in Italy.",
    price: 18900,
    category: "Footwear",
    occasion: ["Formal Evening", "Wedding", "Party"],
    color: ["Gold"],
    sizes: ["36", "37", "38", "39", "40", "41"],
    material: "Metallic Leather",
    images: ["https://images.unsplash.com/photo-1543163521-1bf539c55dd2?w=800"],
    stock: 20,
    sku: "VLR-FW-001",
    tags: ["heels", "sandals", "gold", "evening", "wedding"],
    featured: true,
    rating: 4.7,
    numReviews: 40,
  },
  {
    name: "Black Patent Leather Pumps",
    description: "Timeless pointed-toe pumps in black patent leather with a comfortable 70mm block heel.",
    price: 14200,
    category: "Footwear",
    occasion: ["Business", "Formal Evening"],
    color: ["Black"],
    sizes: ["36", "37", "38", "39", "40", "41"],
    material: "Patent Leather",
    images: ["https://images.unsplash.com/photo-1596703263926-eb0762ee17e4?w=800"],
    stock: 25,
    sku: "VLR-FW-002",
    tags: ["pumps", "heels", "black", "office", "classic"],
    featured: false,
    rating: 4.5,
    numReviews: 31,
  },
  {
    name: "Ivory Suede Clutch",
    description: "A structured hard-shell clutch in ivory suede with a gold-tone clasp. Fits a phone, cards, and lipstick.",
    price: 9800,
    category: "Bags",
    occasion: ["Wedding", "Formal Evening", "Party"],
    color: ["Ivory"],
    sizes: [],
    material: "Suede",
    images: ["https://images.unsplash.com/photo-1566150905458-1bf1fc113f0d?w=800"],
    stock: 18,
    sku: "VLR-BG-001",
    tags: ["clutch", "bag", "ivory", "wedding", "evening"],
    featured: true,
    rating: 4.6,
    numReviews: 14,
  },
  {
    name: "Black Quilted Chain Bag",
    description: "A quilted black leather shoulder bag with a gold chain strap — a signature Valerion silhouette.",
    price: 21900,
    category: "Bags",
    occasion: ["Business", "Casual", "Party"],
    color: ["Black"],
    sizes: [],
    material: "Quilted Leather",
    images: ["https://images.unsplash.com/photo-1584917865442-de89df76afd3?w=800"],
    stock: 13,
    sku: "VLR-BG-002",
    tags: ["bag", "quilted", "chain", "black", "signature"],
    featured: true,
    rating: 4.9,
    numReviews: 52,
  },
  {
    name: "Diamond-Cut Gold Drop Earrings",
    description: "18k gold-plated drop earrings with a hand-set cubic zirconia edge. Lightweight enough for all-day wear.",
    price: 6200,
    category: "Jewelry",
    occasion: ["Formal Evening", "Wedding", "Party"],
    color: ["Gold"],
    sizes: [],
    material: "18k Gold Plated",
    images: ["https://images.unsplash.com/photo-1611591437281-460bfbe1220a?w=800"],
    stock: 30,
    sku: "VLR-JW-001",
    tags: ["earrings", "gold", "jewelry", "evening", "wedding"],
    featured: false,
    rating: 4.5,
    numReviews: 18,
  },
  {
    name: "Silk Charmeuse Scarf",
    description: "A hand-rolled silk charmeuse scarf in a hand-painted botanical print. Doubles as a hair accessory.",
    price: 4500,
    category: "Accessories",
    occasion: ["Casual", "Business", "Resort"],
    color: ["Green", "Gold"],
    sizes: [],
    material: "Silk Charmeuse",
    images: ["https://images.unsplash.com/photo-1601924357840-3e50fbf9b3e5?w=800"],
    stock: 22,
    sku: "VLR-AC-001",
    tags: ["scarf", "silk", "accessory", "print"],
    featured: false,
    rating: 4.4,
    numReviews: 9,
  },
  {
    name: "Burgundy Velvet Blazer Dress",
    description: "A single-piece blazer dress in burgundy velvet, structured at the shoulder with a self-tie waist.",
    price: 19500,
    category: "Dresses",
    occasion: ["Party", "Date Night", "Business"],
    color: ["Burgundy", "Red"],
    sizes: ["XS", "S", "M", "L"],
    material: "Velvet",
    images: ["https://images.unsplash.com/photo-1515372039744-b8f02a3ae446?w=800"],
    stock: 10,
    sku: "VLR-DR-005",
    tags: ["blazer dress", "velvet", "burgundy", "party"],
    featured: false,
    rating: 4.6,
    numReviews: 11,
  },
  {
    name: "White Linen Resort Set",
    description: "A relaxed linen shirt and trouser co-ord in bright white, cut for warm-weather travel.",
    price: 11200,
    category: "Outerwear",
    occasion: ["Resort", "Casual"],
    color: ["White"],
    sizes: ["XS", "S", "M", "L", "XL"],
    material: "100% Linen",
    images: ["https://images.unsplash.com/photo-1517841905240-472988babdf9?w=800"],
    stock: 16,
    sku: "VLR-OW-002",
    tags: ["linen", "resort", "white", "co-ord", "vacation"],
    featured: false,
    rating: 4.3,
    numReviews: 7,
  },
];

export default products;
